format = """
[Isaaruwu]($bold green) \
$env_var\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
🪴 [>>]($bold green) """

[git_branch]
format = "[$branch(:$remote_branch)]($style) "

[git_status]
conflicted = ''
ahead = '⇡'
behind = '⇣'
diverged = ''
up_to_date = '✓'
untracked = ''
stashed = '📦'
modified = ''
staged = '+'
renamed = ''
deleted = ''

[directory]
truncation_length = 8
truncation_symbol = ''

[git_metrics]
added_style = 'bold blue'
deleted_style = 'red'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = true
